### ISSUE TITLE
dbGetInfo() for driver and connection

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RSQLite#117]
As in `?dbGetInfo`.

**Comment by hadley** [comment]
I might be tempted to deprecate these too, in favour of specialised methods.

**Comment by krlmlr** [comment]
I think dbGetInfo() is most useful as input for a default show() implementation. Probably we don't want a specialized method for anything except perhaps max.connections, and a method to clone a connection.

**Comment by krlmlr** [comment]
https://github.com/rstats-db/DBI/issues/53, https://github.com/rstats-db/DBI/issues/54, https://github.com/rstats-db/DBI/issues/55, https://github.com/rstats-db/DBI/issues/56 are a summary of what I think this should look like in the end.

**Comment by hannesmuehleisen** [comment]
@hadley also in favor of deprecation

**Comment by krlmlr** [comment]
Reviving for https://github.com/r-dbi/DBI/issues/271.
