### ISSUE TITLE
REGEXP with RSQLite

### ISSUE THREAD

**Issue by DavorJ** [r-dbi/RSQLite#218]
I am trying to load the regexp.dll library which I compiled with GCC into RSQLite. The regexp.c extension is available in SQLite source.

The extensions is compiled like this:

`gcc ./ext/misc/regexp.c -shared -o ./../export/regexp.dll`

I can load this into my own compiled SQLite CLI, but I cannot load it into RSQLite. Without cygwin1.dll, I get the error: "The specified module could not be found". With cygwin1.dll in PATH the R session crashes. What is going on here?

Can this library not simply be statically linked with RSQLite? Separately compiling and loading these functions is a pain, especially on different platforms.

Cf: https://github.com/rstats-db/RSQLite/issues/85

**Comment by krlmlr** [comment]
We already have a statically linked extension with opt-in, I don't mind adding a second. Would you like to contribute a PR?

**Comment by DavorJ** [comment]
Sorry for my ignorance, but PR? What does that mean?

**Comment by krlmlr** [comment]
Thanks, much appreciated. The CRAN version is very fresh, practically no differences to the development version.

**Comment by krlmlr** [comment]
Implemented in #296.
