### ISSUE TITLE
Remove dbFetch() warning for statements

### ISSUE THREAD

**Issue by ggrothendieck** [r-dbi/RSQLite#227]
The code below gives a dbFetch warning.  Previously that did not occur.  

sqldf does not know whether it is sending a select, create or whatever.  Would like to be able to avoid this warning.

```
library(sqldf)

set.seed(1)
n <- 100
DF1 <- data.frame(a = sample(n, n, replace = TRUE), 
   b = sample(4, n, replace = TRUE), c1 = runif(n))
DF2 <- data.frame(a = sample(n, n, replace = TRUE), 
   b = sample(4, n, replace = TRUE), c2 = runif(n))

result <- sqldf(c("create index ai2 on DF2(a, b)", 
  "select * from DF1 natural join main.DF2"), verbose = TRUE)
```
giving:
```
sqldf: library(RSQLite)
sqldf: m <- dbDriver("SQLite")
sqldf: connection <- dbConnect(m, dbname = ":memory:")
sqldf: initExtension(connection)
sqldf: dbWriteTable(connection, 'DF2', DF2, row.names = FALSE)
sqldf: dbWriteTable(connection, 'DF1', DF1, row.names = FALSE)
sqldf: dbGetQuery(connection, 'create index ai2 on DF2(a, b)')
sqldf: dbGetQuery(connection, 'select * from DF1 natural join main.DF2')
sqldf: dbDisconnect(connection)
Warning message:
In rsqlite_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
```

**Comment by krlmlr** [comment]
Thanks for reporting, I wasn't aware of this use case. Need to think a bit about it.

**Comment by ggrothendieck** [comment]
Here is a different example of this.  This one uses `update`.  It will result in similar warnings.

````
library(sqldf)

BOD$Time[3] <- NA

sqldf(c("update BOD set Time = 0 where Time is null",  "select * from main.BOD"))
````

**Comment by krlmlr** [comment]
All examples contain statements (to be run with `dbExecute()` ) first, and then one query to be run with `dbGetQuery()` . Does `sqldf()` support passing more than one query that returns rows?

**Comment by ggrothendieck** [comment]
I have just encountered this warning on some other older software. This is only the zillionth time I have encountered it. It really is frustrating that older software generates all these warnings.  It would be nice if there were a global option, say, to turn these warnings off.  e.g. `options(RSQLite.dbFetchWarning = FALSE)`  The warning message should include a pointer to that option, e.g.

```
SQL statements should be issued with dbExecute() or dbSendStatement() 
instead of dbGetQuery() or dbSendQuery() 
or else set this option:  `options(RSQLite.dbFetchWarning = FALSE)`
```

Even better would be to just get rid of this warning entirely.  This is basic infrastructure and really ought to be backwards compatible IMHO.


Also it would be nice if the warning message had some \n characters in it since it typically goes off the screen to the right so you can easily miss parts of it.

**Comment by krlmlr** [comment]
I think the solution here is to call `dbFetch()` only if there's something to fetch. One way to find out is to check [`dbHasCompleted()`](dbhascompleted), it is `FALSE` for queries but `TRUE` for statements.

The warning is good, it points to an unintended use of the interface. In user code you can `suppressWarnings()` or use a more elaborate `tryCatch(..., warning = function(e) { if (...) ... else warning(e) })`, package code really should be more careful.
