### ISSUE TITLE
dbGetQuery() no longer returns row_names in 'SELECT *'

### ISSUE THREAD

**Issue by mfoos** [r-dbi/RSQLite#229]
Hi, I see here https://cran.r-project.org/web/packages/RSQLite/news.html that row.names newly defaults to false for a handful of functions, so I expect this is a "feature" but a) it broke a lot of my code (I use row names because I store matrices! Don't judge me! 😝 )  and b) it's not super clear in the documentation that this is newly the case. So I guess my request is to either roll it back or update the docs. Thanks!

Incidentally, it looks like `pkgconfig::set_config("RSQLite::row.names.query" = NA)` does bring my code back into function, but I haven't tested it extensively yet.

**Comment by krlmlr** [comment]
Thanks. The documentation reflects the status quo and not the past, this is what NEWS is for ;-)

Please let me know if `set_config()` works for you.

**Comment by mfoos** [comment]
oh my, I see I failed to make my most important part - NEWS doesn't list dbGetQuery() as one of the handful of functions affected by the new version. And actually if I look in the "man page" for dbGetQuery(), it says "A column named row_names is treated like any other column." - which, to me, says "will be returned in a select *". Thanks!

**Comment by krlmlr** [comment]
Edited NEWS.
