### ISSUE TITLE
duplicated column names

### ISSUE THREAD

**Issue by ggrothendieck** [r-dbi/RSQLite#230]
This gives an error which is not easily understandable as being caused by duplicate column names. Not sure if it is worth it to address it or if it would be better done in the SQLite code.  

```
library(RSQLite)
dd <- data.frame(1,2)
names(dd) <- c("a", "a")

con <- dbConnect(SQLite())
dbWriteTable(con, "dd", dd)
```

If one uses RH2 and the H2 database similar code does give an understandable error message identifying the problem as a duplicated column name and identifying the dupliated column name.

```
library(RH2)
con <- dbConnect(H2())
dbWriteTable(con, "dd", dd) # dd defined above
```

**Comment by krlmlr** [comment]
Thanks, confirmed.

**Comment by krlmlr** [comment]
I see now:

``` r
library(RSQLite)
dd <- data.frame(1, 2)
names(dd) <- c("a", "a")

con <- dbConnect(SQLite())
dbWriteTable(con, "dd", dd)
#> Error: duplicate column name: a
```

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
