### ISSUE TITLE
max number of columns

### ISSUE THREAD

**Issue by ggrothendieck** [r-dbi/RSQLite#235]
Suggest documenting how to increase the maximum number of columns. See:

https://stackoverflow.com/questions/41586868/error-in-r-using-sqldf-too-many-sql-variables/46836205#46836205

**Comment by krlmlr** [comment]
I wonder if it's worthwhile to increase the compile-time limit and then lower it during run time: https://sqlite.org/limits.html. Would that have an impact on performance?

**Comment by krlmlr** [comment]
[DuckDB](https://www.duckdb.org/) works much better with many columns than SQLite.

**Comment by mstr3336** [comment]
Hi - 
I'm currently facing this problem, and I'm wondering what I actually have to do in order to change the compile time limit in my own fork of this package?

**Comment by mstr3336** [comment]
Just following up on this - The following pointed me in the right direction. https://github.com/r-dbi/RSQLite/issues/195#issuecomment-269540309

My first instinct had been to change the limits in Makevars, however this was failing initially. Moving the limit changes to the start of `PKG_CPP_FLAGS`, preceding `-I.` seems to have resolved this.

**Comment by mstr3336** [comment]
My makevars:
```
# BOOST_NO_AUTO_PTR: https://github.com/eddelbuettel/bh/issues/57#issuecomment-406261595
PKG_CPPFLAGS= \
             -DSQLITE_MAX_VARIABLE_NUMBER=40000 \
             -DSQLITE_MAX_COLUMN=30000 \
             -I. \
             -DRSQLITE_USE_BUNDLED_SQLITE \
             -DSQLITE_ENABLE_RTREE \
             -DSQLITE_ENABLE_FTS3 \
             -DSQLITE_ENABLE_FTS3_PARENTHESIS \
             -DSQLITE_ENABLE_FTS5 \
             -DSQLITE_ENABLE_JSON1 \
             -DSQLITE_ENABLE_STAT4 \
             -DSQLITE_SOUNDEX \
             -DRCPP_DEFAULT_INCLUDE_CALL=false \
             -DRCPP_USING_UTF8_ERROR_STRING \
             -DBOOST_NO_AUTO_PTR 

PKG_CXXFLAGS=$(CXX_VISIBILITY)
PKG_CFLAGS=$(C_VISIBILITY)

PKG_LIBS = vendor/sqlite3/sqlite3.o

.PHONY: all

all: $(SHLIB)

$(SHLIB): $(PKG_LIBS)
```

I did notice that this stopped me from geting an "Error: too many SQL variables" when performing certain operations on an SQLite backended cache, however, now those operations seems to just use all of my node's memory, until the R process is killed.
