### ISSUE TITLE
Automatically initialise extensions

### ISSUE THREAD

**Issue by hadley** [r-dbi/RSQLite#236]
There doesn't seem to be any harm to this.  If necessary, could include an argument in `dbConnect` method allowing you to suppress it if you really wanted.

**Comment by krlmlr** [comment]
We already have the `loadable.extensions` argument to `dbConnect()`, if it's `FALSE` then `initExtension()` fails. Do we need another argument?

**Comment by hadley** [comment]
Yeah that'd be great - maybe `default.extensions = TRUE`?
