### ISSUE TITLE
dbWriteTable() not working when the "party" package is loaded

### ISSUE THREAD

**Issue by gpfymedia** [r-dbi/RSQLite#239]
After loading the package "party" (same happens with "partykit") on debian jessie dbWriteTable stops working for (and only for) RSQLite

```
library(RSQLite)
con=dbConnect(drv=dbDriver("SQLite"))
dbWriteTable(con,"cars",cars,overwrite=T)
# everything fine
library(party) #or library(partykit)
dbWriteTable(con,"cars",cars,overwrite=T)
# Error: C stack usage  7969444 is too close to the limit
```

I have tried installing development version due to the answer to issue #177. But the problem 
didn't get solved

linux debian jessie
R version 3.4.1
DBI version  0.1-6
RSQLite version 2.0-10
party version 1.2-3

notes:
I have tried to reproduce the error on windows but everything is OK there.
I have tried to repdroduce the problem with RSQLite version 1.1-2 and everything is OK also.

**Comment by krlmlr** [comment]
Thanks, confirmed on Ubuntu with R 3.4.3.

**Comment by krlmlr** [comment]
Sorry: No, can't confirm on Ubuntu. Can you please update the DBI package and retest?
