### ISSUE TITLE
Improve error message when writing dataframe with unsupported data type

### ISSUE THREAD

**Issue by arencambre** [r-dbi/RSQLite#246]
I found the hard way that SQLite does not support date types. This discovery could have been short circuited had RSQLite given me useful information when I attempted to use **dbWriteTable** with a dataframe that had a POSIXlt type. The error message I get is:
```
Error in rsqlite_bind_rows(rs@ptr, value) : 
  Parameter 2 does not have length 11.
```

To make sense of this, you'd have to be intimately familiar with RSQLite's innards. That error is almost absent on Google, even when omitting the digits. Finding **rsqlite_bind_rows** in the appropriate .cpp file in this repository shed no useful light on the issue. Had I not stumbled across the answer in an unrelated exploration, problem diagnosis would have taken a long time.

Throw us a bone: if the data type in my dataframe is why the data can't be saved, please let me know this.

**Comment by krlmlr** [comment]
Thanks, I agree *RSQLite* could be more helpful here.

**Comment by tomastelensky** [comment]
Why does RSQLite doesn't accept data.frames with POSIXlt columns? Is there special bugreport for that?

**Comment by krlmlr** [comment]
SQLite doesn't know about date and time types. Can you convert to character before writing to the database?

**Comment by arencambre** [comment]
@krlmlr you could, and that could be fine. My request is that RSQLite inform us with a useful error when we mistakenly try to save a date or time type.

**Comment by krlmlr** [comment]
Let's do it as part of #333 that deals with proper support for date and time columns.
