### ISSUE TITLE
should `RSQLite:::rsqlite_import_file` break if problem row happens beyond extent of desired import?

### ISSUE THREAD

**Issue by ajdamico** [r-dbi/RSQLite#248]
hi, question..here's a malformed csv file at row 3.  if the user only wants rows 1 and 2, should the import throw an error?

	library(DBI)
	tf <- tempfile()
	writeLines( "1,2\n3,4\n5" , tf )
	db <- dbConnect( RSQLite::SQLite() )
	dbWriteTable( db , 'x' , tf , nrows = 2 , header = FALSE )

thanks!

**Comment by krlmlr** [comment]
It should, but currently does not, see #249.

**Comment by krlmlr** [comment]
Throwing an error now:

``` r
library(DBI)
tf <- tempfile()
writeLines("1,2\n3,4\n5", tf)
db <- dbConnect(RSQLite::SQLite())
dbWriteTable(db, "x", tf, nrows = 2, header = FALSE)
#> Error in connection_import_file(conn@ptr, name, value, sep, eol, skip): RS_sqlite_import: /tmp/RtmpV0PNWz/file140217dfcc56 line 3 expected 2 columns of data but found 1
```

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
