### ISSUE TITLE
how to find the probability value of chart 

### ISSUE THREAD

**Issue by msheranga** [r-dbi/RSQLite#254]
I build the decision tree for some studies after plotting the decision tree  

![image](https://user-images.githubusercontent.com/37143766/37451625-16c60bda-2858-11e8-92f9-66ddcf1ca4ec.png)
how to get the y values to data frame please help
as a example node 3 y values 0.748 and 0.252

**Comment by krlmlr** [comment]
This has nothing to do with RSQLite. Please ask on StackOverflow or a similar venue.
