### ISSUE TITLE
Couldn't set synchronous mode: disk I/O error

### ISSUE THREAD

**Issue by barrykui** [r-dbi/RSQLite#255]
Can't connected with the database?  errors are below: 
```
> db <- dbConnect(RSQLite::SQLite(), dbname="Test.sqlite")
Warning message:
Couldn't set synchronous mode: disk I/O error
Use `synchronous` = NULL to turn off this warning. 
```

Any one helps? Thank you!!!!!

**Comment by krlmlr** [comment]
Thanks. Is there anything special about the file location? Is it on a network drive? Are there permission restrictions? What OS are you using?
