### ISSUE TITLE
Identical column names imported, problem with dplyr functions

### ISSUE THREAD

**Issue by bpbraun** [r-dbi/RSQLite#257]
This is my first post to an issue on github or other site so please excuse any etiquette violations--I promise I will learn quickly.

The query to my database returns a data frame with two identical columns for the "join by" column.  This isn't really a problem in and of itself, but the issue is that each of the column names are identical.  This means I can't apply dplyr functions (like select, mutate, distinct, etc) because they aren't unique (I get an error that the there is a duplicated column or that it's not a "dictionary).

When columns with the same heading are merged with the dplyr functions, one of them is given an identifier (like an _1) and I feel like that should be the case here.

**Comment by krlmlr** [comment]
Thanks. The description was very clear, usually a [reprex](http://reprex.tidyverse.org/) is very helpful.

In the future, DBI will require unique column names in data frames returned from `dbFetch()` (and consequently `dbGetQuery()` and `dbWriteTable()`): https://github.com/r-dbi/DBItest/issues/137. RSQLite will adhere to this requirement. Until then, please use `df <- tibble::set_tidy_names(df)` or `names(df) <- make.unique(names(df))` on the returned data frame.
