### ISSUE TITLE
SQLite Update Hook

### ISSUE THREAD

**Issue by dhofstetter** [r-dbi/RSQLite#258]
Is it possible to include the sqlite Update Hook somehow? This would be an interesting feature for shiny apps, if multiple sessions are going to use the same persistent data. For this case the update notification might be used for triggering updates in the UI probably.

```
SQLITE_API` void *sqlite3_update_hook(
  sqlite3*, 
  void(*)(void *,int ,char const *,char const *,sqlite3_int64),
  void*
);
```

BR Daniel

**Comment by krlmlr** [comment]
Are you sure this hook is called when another session updates the data? When will it be called?

**Comment by dhofstetter** [comment]
As long as it is the same underlying connection it will work. So any connection established in global.R e.g. should work.

To provide this feature consistent, for use with pool library e.g. I think the dbi interface needs to be extended as well

**Comment by krlmlr** [comment]
So this means that it works only for updates within the same R session. The good news is that this means that hook functions can be called synchronously.

Can you point me to a Shiny app that would benefit from such an extension?
