### ISSUE TITLE
out of disk space error message unclear

### ISSUE THREAD

**Issue by mschilli87** [r-dbi/RSQLite#261]
@hadley [suspects](https://github.com/tidyverse/dplyr/issues/3615#event-1669631234) you are to blame for https://github.com/tidyverse/dplyr/issues/3615 so I'm opening this here. :wink:

---
In short: I ran out of disk space writing a tibble to a local SQLite database and got the error

```
Error in result_create(conn@ptr, statement) :
  cannot rollback - no transaction is active
```

which was not particularly helpful to understand that the problem was a full disk. :wink:

**Comment by krlmlr** [comment]
Thanks. Could you please make this issue more complete by including the relevant code?

**Comment by mschilli87** [comment]
Sure, I thought the link with example was sufficient.
Anyways it will be reprocuible only if you run out of disk space.

```r
library(RSQLite)
library(dplyr)

# create SQLite connection on tmpfile (no NFS!)
tmp.sqlite <- tempfile(fileext = ".sqlite")
tmp.db <- dbConnect(SQLite(), dbname = tmp.sqlite)

# try to write a tibble
mtcars %>%
as_data_frame %>%
copy_to(dest = tmp.db, name = "mtcars", temporary = FALSE,
        overwrite = TRUE)

# close database connection
dbDisconnect(tmp.db)
````

**Comment by krlmlr** [comment]
Testing strategy: https://stackoverflow.com/a/16044420/946850.

**Comment by krlmlr** [comment]
Thanks. On a database on a 1 MB file system mounted on `./mount`, I'm now seeing with the following example:

```
library(RSQLite)

# create SQLite connection on tmpfile (no NFS!)
tmp.sqlite <- tempfile(tmpdir = "./mount", fileext = ".sqlite")
tmp.sqlite
tmp.db <- dbConnect(SQLite(), dbname = tmp.sqlite)

for (i in 1:10000) {
  dbWriteTable(tmp.db, "beaver", beaver2, append = TRUE)
}
## Error: database or disk is full
```
