### ISSUE TITLE
SQLite -> 3.24

### ISSUE THREAD

**Issue by ankane** [r-dbi/RSQLite#262]
Hi, thanks for this great project!

SQLite 3.24 [was released](https://sqlite.org/changes.html) in early June and adds support for upsert 🎉 

I'm happy to submit a PR, but also understand if you prefer to have a maintainer run it for security. Please let me know.

**Comment by krlmlr** [comment]
Done. Too bad window functions aren't part of this release yet.

**Comment by ankane** [comment]
Thanks @krlmlr 👍

**Comment by ankane** [comment]
@krlmlr Great news - window functions are supported as of 3.25.0! Current version is now 3.25.2. https://www.sqlite.org/changes.html
