### ISSUE TITLE
extension median ignores LIMIT

### ISSUE THREAD

**Issue by mnr** [r-dbi/RSQLite#267]
It appears that the "median" extension to RSQLite ignores line selectors such as ORDER BY and LIMIT.

For example - using the attached database...

```
# install.packages("RSQLite")
library(DBI)

SQLiteIsHere <- "ucs_satellite.db" 
mySQLiteDB <- dbConnect(RSQLite::SQLite(),SQLiteIsHere)

RSQLite::initExtension(mySQLiteDB)

randomMedianSQL <- function() {
  do_this_sqlite <- "
    SELECT median(`Launch Mass (kg.)`)
    FROM satellites
    WHERE `Launch Mass (kg.)` != ''
    ORDER BY RANDOM()
    LIMIT 100
  "
  
  median(dbGetQuery(mySQLiteDB,do_this_sqlite))
}

randomMedianSQL() # returns 700
```

700 is the median of ALL values in the database.
i.e.
`median(UCS_Satellite_Database$Launch.Mass..kg.., na.rm = TRUE)`
returns 700.

It appears that median is ignoring the last two lines:
```
    ORDER BY RANDOM()
    LIMIT 100
```

My thanks for your work on this!

[ucs_satellite.db.zip](https://github.com/r-dbi/RSQLite/files/2330269/ucs_satellite.db.zip)

**Comment by krlmlr** [comment]
Thanks. From reading the SQL query it seems that the `LIMIT 100` is applied to the one-row summary table that is returned from `SELECT median(...) FROM satellites` . You could use a subquery, or perhaps use _dplyr_ syntax with _dbplyr_.

**Comment by krlmlr** [comment]
``` r
library(DBI)


con <- dbConnect(RSQLite::SQLite())

dbWriteTable(con, "test", data.frame(a = 1:200))
dbGetQuery(con, "SELECT max(a) FROM test LIMIT 100")
#>   max(a)
#> 1    200
dbGetQuery(con, "SELECT max(a) FROM (SELECT * FROM test LIMIT 100)")
#>   max(a)
#> 1    100
```

<sup>Created on 2018-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
