### ISSUE TITLE
new sqlite has window functions! what needs to be done to update to that version?

### ISSUE THREAD

**Issue by RMHogervorst** [r-dbi/RSQLite#268]
I love SQLite and  how we can leverage that within R. I noticed the new version of sqlite has window functions. What needs to be done to add that functionality /version to RSQLite? Can I help in any way?
Do we need to rewrite some DBI things?

**Comment by RMHogervorst** [comment]
apparently it is very much like postgresql so we can probably port over some of that code

**Comment by hermandr** [comment]
+1 to upgrade to 3.25 please

**Comment by krlmlr** [comment]
Can you please test-drive

```r
remotes::install_github("r-dbi/RSQLite#273")
```

and let me know if it works for you?

**Comment by ankane** [comment]
Working great for me 👍 Thanks @krlmlr

**Comment by RMHogervorst** [comment]
all general functions seem to work, but
I believe the window functions are not yet implemented?

```
library(RSQLite)
library(dplyr)
library(dbplyr)
con <- dbConnect(RSQLite::SQLite(), ":memory:")

dbListTables(con)
dbWriteTable(con, "mtcars", mtcars)
dbListTables(con)

mtcars <- tbl(con, "mtcars")
mtcars %>% 
    group_by(cyl) %>% 
    mutate(mpg_cum = mpg+lag(mpg, n = 1,default = 0,order_by = hp))
mtcars %>% 
    group_by(cyl) %>% 
    mutate(min_rank = min_rank(mpg))
```
`Error: Window function `lag()` is not supported by this database`
`Error: Window function `rank()` is not supported by this database`

**Comment by RMHogervorst** [comment]
But I guess updating sqlite and updating the DBI layer should be two atomic commits right?

**Comment by ankane** [comment]
The examples I tried from this page work: https://www.sqlite.org/windowfunctions.html

```r
library(DBI)

db <- dbConnect(RSQLite::SQLite(), dbname=":memory:")

dbExecute(db, "CREATE TABLE t0(x INTEGER PRIMARY KEY, y TEXT)")
dbExecute(db, "INSERT INTO t0 VALUES (1, 'aaa'), (2, 'ccc'), (3, 'bbb')")

res <- dbSendQuery(db, "SELECT x, y, row_number() OVER (ORDER BY y) AS row_number FROM t0 ORDER BY x")
print(dbFetch(res))
```

**Comment by RMHogervorst** [comment]
ah! of course! it is dbplyr specific! Thanks!

**Comment by krlmlr** [comment]
This will auto-close when the PR is merged.
