### ISSUE TITLE
Can't access database with RSQLite 2.1.1

### ISSUE THREAD

**Issue by R-fred** [r-dbi/RSQLite#271]
Using RSQLite 2.1.x with RStudio Desktop 1.1.463 (or 1.2 preview) on Windows 10 Home 64 bit (latest update as of 05.11.2018), I can not connect to my sqlite database nor can I create a new one.
Tried also on Ubuntu 18.04 64 bit, RStudio server 1.1.383.

This issue comes up on R3.3.3, R3.4.4 and R3.5.1, MS R Open 3.5.1 on windows (all 64 bit) and R3.4.4 on Ubuntu 18.04 64 bit.

The sqlite database (see zip file) can be opened and worked on using a variety of database tools (e.g. DBeaver, SQLiteStudio, DB Browser for SQLite).
However, with RSQLite, triying to list the tables with dbListTables returns "character(0)" eventhough 3 tables are present.
Creating a new database also does not work.

[volleyballR_db.zip](https://github.com/r-dbi/RSQLite/files/2550806/volleyballR_db.zip)

**Comment by R-fred** [comment]
I looked more into it and here is what I found.

The database was part of an project (.RProj) with git. Once I leave the project, I am able to access the database again and get  a list of all tables.

Removing the .RHistory and .RData from the project folder had the same effect.

All good, not real fault of RSQLite I guess...

**Comment by krlmlr** [comment]
Thanks for the heads-up. I recommend turning off saving `.RData` files, and always explicitly save all results that are needed later.
