### ISSUE TITLE
dbListTables lists a table but dbExistsTable says it doesn't exist

### ISSUE THREAD

**Issue by joethorley** [r-dbi/RSQLite#275]
The following code demonstrates the problem
```r
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
DBI::dbCreateTable(con, "`loCal`", mtcars)
DBI::dbListTables(con) # lists table 
DBI::dbExistsTable(con, "`loCal`") # but says it doesn't exist
DBI::dbDisconnect(con)
```

**Comment by krlmlr** [comment]
Thanks, confirmed. This problem seems to be restricted to table names that start and end with a backtick.

Need to use

```r
name <- dbUnquoteIdentifier(conn, dbQuoteIdentifier(conn, name))[[1]]@table
```

in `sqliteListTablesWithName()`, but this should then also work with identifiers that contain a schema.
