### ISSUE TITLE
regexp_replace

### ISSUE THREAD

**Issue by ggrothendieck** [r-dbi/RSQLite#282]

**Comment by ggrothendieck** [comment]
It would be nice to have the `regexp_replace` function available in RSQLite.  Source code is here:
https://github.com/gwenn/sqlite-regex-replace-ext

**Comment by krlmlr** [comment]
Thanks for reaching out. I don't mind adding it, would you like to contribute a pull request?

**Comment by ggrothendieck** [comment]
Sorry, I am overloaded and personally can just use that function in h2 but I do think it would be useful in general if you want to do the work of adding it and since the source code is already available I thought I would mention  it.

**Comment by krlmlr** [comment]
Does #296 solve this?

**Comment by ggrothendieck** [comment]
Yes, if the solution there works that would address this.

**Comment by krlmlr** [comment]
Thanks for the heads-up. Please open a new issue if this turns out to be insufficient.
