### ISSUE TITLE
Syntax Error using ON CONFLICT in UPSERT

### ISSUE THREAD

**Issue by norrisp90** [r-dbi/RSQLite#285]
RSQLite appears to throw a syntax error using the SQLite ON CONFLICT method when used in UPSERTS even-though the SQL generated is valid and will run fine on the database if executed there directly.

SQLite version 3.24.0
See: https://www.sqlite.org/lang_UPSERT.html
See: https://sqlite.org/lang_conflict.html

Error: : near "ON": syntax error

**Comment by krlmlr** [comment]
Thanks. Could you please provide a reproducible example? Please see https://reprex.tidyverse.org/ for guidance.

**Comment by ankane** [comment]
Hey @norrisp90, the latest version on CRAN uses SQLite 3.22.0, which doesn't have upsert. You'll need to install the master branch from GitHub to use it.

**Comment by krlmlr** [comment]
Thanks. @norrisp90: Which version of RSQLite (the R package) are you using?
