### ISSUE TITLE
Allow named supersets

### ISSUE THREAD

**Issue by Kodiologist** [r-dbi/RSQLite#286]
If you have a big named list or dataframe and you want to interpolate a few of its items into a parametrized statement, it would be nice to be able to say

     dbGetQuery(db,
         "select * from T where
             part = :partnumber and place = :city",
         mylist)

But as is, this code produces the error `Named parameters not used in query`. `db_bind` has a parameter `allow_named_superset`, but there's no way to pass `allow_named_superset = TRUE` because `dbBind` forces `allow_named_superset = FALSE`.

**Comment by krlmlr** [comment]
Thanks for raising this.

The checks are there to make sure that the parameters correspond to the query. The internal `allow_named_superset` argument was a compatibility measure, not intended to be exposed with the new API.

Could you expand a bit on your use case?

**Comment by Kodiologist** [comment]
The case where it bit me is in this program where I'm pulling down a lot of data from a web service that produces JSON objects. I get these large objects with like 30 elements when I'm only interested in 5 or 10. The obvious way to write this is like

    dbGetQuery(db,
        "insert into T values (:partnumber, :city, :state)",
        obj)

, but in order for this to work, you need to write the redundant

    dbGetQuery(db,
        "insert into T values (:partnumber, :city, :state)",
        obj[c("partnumber", "city", "state")])

. You can avoid the redundancy with something like

    dbGetQuery(db,
        "insert into T values (?, ?, ?)",
        unname(obj[c("partnumber", "city", "state")]))

but it would be nice to not have to count the question marks. (A related bit of hypervigilance on the part of RSQLite is that the `unname` is necessary here or else RSQLite will complain about using a named list to fill in positional parameters, even though R named lists are ordered.)

For now, I'm resorting to generating the SQL statement dynamically with

    keys = c("partnumber", "city", "state")
    dbGetQuery(db,
        sprintf("insert into T values (%s)",
            paste(collapse = ", ", rep("?", length(keys)))),
        unname(obj[keys]))

which is a hassle.

**Comment by krlmlr** [comment]
Have you considered using the new `dbAppendTable()` ?

**Comment by Kodiologist** [comment]
Interesting, I wasn't aware of that. Thanks. I'll try it out.

**Comment by Kodiologist** [comment]
To be clear, `dbAppendTable` is nice and I've made use of it, but I'd still appreciate allowing named supersets for things like updates.

**Comment by krlmlr** [comment]
I believe the safety checks do more good than harm -- it seems more likely that a mismatch between parameters is an accident than a deliberate choice. In your situation, a helper function that composes the SQL query based on the parameters looks like a good choice.

**Comment by Kodiologist** [comment]
> it seems more likely that a mismatch between parameters is an accident than a deliberate choice

I would think the opposite. But in any case, even if you like these checks, why not allow those who don't want them to bypass them, as with the parameter `allow_named_superset = TRUE`, which is already mostly implemented? Yes, generating the statement dynamically is what I do now, and I can continue to do that, but isn't it a bit silly for me to do all that song and dance just because I need to avoid a false positive from a check for a possible bug that I don't want in the first place?
