### ISSUE TITLE
SQLite 3.28.0

### ISSUE THREAD

**Issue by ankane** [r-dbi/RSQLite#289]
Hey @krlmlr, it looks like SQLite 3.28.0 was released last month. Would be great to pull the latest version and get a new release out. I have [a branch](https://github.com/ankane/RSQLite/tree/sqlite328) and can submit a PR, but for security reasons, think it's best for you to run the upgrade script. Let me know if I can help at all.

**Comment by hannesmuehleisen** [comment]
+1 because window functions!

**Comment by krlmlr** [comment]
Closed in #292.
