### ISSUE TITLE
Issue with integer64 overflow in RSQLite

### ISSUE THREAD

**Issue by mskyttner** [r-dbi/RSQLite#291]
I am attempting to create an R package which uses RSQLite to read and return some data into a tibble. When calling calling `collect()` on the RSQLite connection it appears that a sqlite int column silently gets converted to integr64 but with an overflow, in this case resulting in population counts appearing to be negative (the converted value seems to be the minimum of a signed 32 bit integer value rather than a 64 bit integer value).

Here is the code to reproduce the issue:

``` r
# uncomment and run this first to get the data
#install_github("mskyttner/factbook", build_vignettes = "TRUE")

library(factbook)
library(dplyr)

# version of RSQLite: 2.1.1
# version of dplyr: 0.8.1

# first get the sqlite db locally
factbook_download()

# get a db connection to an sqlite db
src <- factbook:::src_sqlite_factbook()

# get data from the 'facts' table
res <- src %>% tbl("facts")

# as expected this returns no matches
res %>%
  filter(population < 0)
```

    ## # Source:   lazy query [?? x 13]
    ## # Database: sqlite 3.22.0 [/home/rstudio/.config/factbook/factbook.db]
    ## # … with 13 variables: id <int>, code <chr>, name <chr>, area <int>,
    ## #   area_land <int>, area_water <int>, population <int>,
    ## #   population_growth <dbl>, birth_rate <dbl>, death_rate <dbl>,
    ## #   migration_rate <dbl>, created_at <dbl>, updated_at <dbl>

``` r
# after collect(), the same thing returns 19 matches
res %>%
  collect() %>%
  filter(population < 0)
```

    ## # A tibble: 19 x 13
    ##       id code  name   area area_land area_water population population_grow…
    ##    <int> <chr> <chr> <int>     <int>      <int> <integr64>            <dbl>
    ##  1   198 at    Ashm…     5         5          0 -21474836…               NA
    ##  2   201 cr    Cora…     3         3          0 -21474836…               NA
    ##  3   202 hm    Hear…   412       412          0 -21474836…               NA
    ##  4   208 ip    Clip…     6         6          0 -21474836…               NA
    ##  5   210 fs    Fren…    NA        NA         NA -21474836…               NA
    ##  6   222 bv    Bouv…    49        49          0 -21474836…               NA
    ##  7   223 jn    Jan …   377       377          0 -21474836…               NA
    ##  8   228 io    Brit… 54400        60      54340 -21474836…               NA
    ##  9   240 sx    Sout…  3903      3903          0 -21474836…               NA
    ## 10   244 bq    Nava…     5         5          0 -21474836…               NA
    ## 11   248 wq    Wake…     6         6          0 -21474836…               NA
    ## 12   249 um    Unit…    NA        NA         NA -21474836…               NA
    ## 13   252 pf    Para…     7         7          0 -21474836…               NA
    ## 14   253 pg    Spra…     5         5          0 -21474836…               NA
    ## 15   256 xq    Arct…    NA        NA         NA -21474836…               NA
    ## 16   257 zh    Atla…    NA        NA         NA -21474836…               NA
    ## 17   258 xo    Indi…    NA        NA         NA -21474836…               NA
    ## 18   259 zn    Paci…    NA        NA         NA -21474836…               NA
    ## 19   260 oo    Sout…    NA        NA         NA -21474836…               NA
    ## # … with 5 more variables: birth_rate <dbl>, death_rate <dbl>,
    ## #   migration_rate <dbl>, created_at <chr>, updated_at <chr>

``` r
# unexpected... and this displays warning about integer overflow
res %>%
  collect() %>%
  mutate_if(bit64::is.integer64, as.integer) %>%
  filter(population < 0)
```

    ## Warning in as.integer.integer64(population): NAs produced by integer
    ## overflow

    ## # A tibble: 0 x 13
    ## # … with 13 variables: id <int>, code <chr>, name <chr>, area <int>,
    ## #   area_land <int>, area_water <int>, population <int>,
    ## #   population_growth <dbl>, birth_rate <dbl>, death_rate <dbl>,
    ## #   migration_rate <dbl>, created_at <chr>, updated_at <chr>

``` r
# but converting population to character then to numeric works
res %>%
  mutate(population_chr = as.character(population)) %>%
  mutate(pop = as.numeric(population_chr)) %>%
  select(pop) %>%
  pull(pop) %>%
  max(na.rm = TRUE)
```

    ## [1] 7256490011

``` r
# am I doing it wrong? or is this expected behaviour?

# info about the data source as given by sqlite3 from CLI:

# sqlite> select population from facts order by population desc limit 5;
# 7256490011
# 1367485388
# 1251695584
# 513949445
# 321368864

# sqlite> .schema
# CREATE TABLE "facts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "area" integer, "area_land" integer, "area_water" integer, "population" integer, "population_growth" float, "birth_rate" float, "death_rate" float, "migration_rate" float, "created_at" datetime, "updated_at" datetime);
# CREATE VIRTUAL TABLE fts using fts5(country);
# CREATE TABLE 'fts_data'(id INTEGER PRIMARY KEY, block BLOB);
# CREATE TABLE 'fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
# CREATE TABLE 'fts_content'(id INTEGER PRIMARY KEY, c0);
# CREATE TABLE 'fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
# CREATE TABLE 'fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
```

**Comment by mskyttner** [comment]
May be related to #243 but happens not a writing but when reading an integer column from SQLite3 and doing `collect()` where it seems that an integr64 value gets silently converted into a 32 bit integer with an overflow.

**Comment by krlmlr** [comment]
Thanks, confirmed. Smaller reprex:

``` r
library(DBI)

con <- dbConnect(RSQLite::SQLite())

x <- data.frame(a = bit64::as.integer64(c(10L, NA, 1e10)))

dbWriteTable(con, "a", x, append = TRUE)
dbReadTable(con, "a")
#>             a
#> 1          10
#> 2 -2147483648
#> 3 10000000000
```

<sup>Created on 2019-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
