### ISSUE TITLE
RSQLite download - Entry point Not Found

### ISSUE THREAD

**Issue by joshua-goldman98** [r-dbi/RSQLite#293]
I am trying to manually install RSQLite. I have successfully installed all of the dependencies. Unfortunately, when I attempt to use RSQLite an error appears. At the top of the error it says rsession.exe - Entry Point Not Found. The actual error message is : The procedure entry point R_ContinueUnwind could not be located in the dynamic link library. Then it shows the path to the file RSQLite.dll. I am not sure how to fix this. I think one way to fix this may to find a new download of RSQLite. Besides that I do not know what to do.

**Comment by krlmlr** [comment]
What version of R are you using? Are you on Windows? What do you mean by "manually install RSQLite"?

**Comment by joshua-goldman98** [comment]
I am using 3.5.3
Yes, I am on windows.
By manually install I mean I am downloading the package directly from https://cran.r-project.org/web/packages/RSQLite/index.html and then I am attempting to use the install packages tool.

**Comment by krlmlr** [comment]
Strange. What happens if you run `install.packages("RSQLite")` (if you can connect to CRAN)?
