### ISSUE TITLE
Create a new CRAN release?

### ISSUE THREAD

**Issue by schuemie** [r-dbi/RSQLite#294]
Sorry for bugging, but it would really help if a new version was released to CRAN. 

Really all I need is the [update to SQLite 3.25.3](https://github.com/r-dbi/RSQLite/commit/c19998cd003fae22616db070c754cedd8532e6b3), since that supports things like ROW_NUMBER().

**Comment by krlmlr** [comment]
On its way, planned when binaries for {blob} are built.

**Comment by georgevbsantiago** [comment]
The `blob 1.2.0`  package was made available on CRAN!  :clap: :clap: :clap:

**Comment by krlmlr** [comment]
See #298.
