### ISSUE TITLE
Multicore SQLite

### ISSUE THREAD

**Issue by Hamedhm** [r-dbi/RSQLite#295]
Hi

I get the following error message when I try to write to a SQLite DB file on a cluster computing machine: Couldn't set synchronous mode: database is locked

I know the cause that is several cores try to write to the same DB at or nearly the same time. Then the locking mechanism leads to the error. I am wondering whether the Serialized option can solve this issue? See https://www.sqlite.org/threadsafe.html

**Comment by krlmlr** [comment]
Thanks.

The following example starts 10 worker processes that write to the same table 100 times. This seems to work. What am I doing differently?

``` r
library(tidyverse)

dbfile <- tempfile("race", ".sqlite")

fun <- function(dbfile) {
  con <- DBI::dbConnect(RSQLite::SQLite(), path = dbfile)
  for (i in 1:100) {
    DBI::dbWriteTable(con, "a", data.frame(a = 1), overwrite = TRUE)
  }
}

processes <- map(
  1:10,
  ~ callr::r_bg(
    fun,
    list(dbfile = dbfile)
  )
)

map(processes, ~ .$read_all_error_lines())
#> [[1]]
#> character(0)
#> 
#> [[2]]
#> character(0)
#> 
#> [[3]]
#> character(0)
#> 
#> [[4]]
#> character(0)
#> 
#> [[5]]
#> character(0)
#> 
#> [[6]]
#> character(0)
#> 
#> [[7]]
#> character(0)
#> 
#> [[8]]
#> character(0)
#> 
#> [[9]]
#> character(0)
#> 
#> [[10]]
#> character(0)
```

<sup>Created on 2019-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Hamedhm** [comment]
It seems that it is an IO issue, I put a (random value) pause in the code and it fixed the issue.

Just for your example, your code actually writes something very small, however, I write a significantly bigger record.
