### ISSUE TITLE
number of characters in a sql command

### ISSUE THREAD

**Issue by Jon-Steve** [r-dbi/RSQLite#299]
Hello,
I try to cerate a complex SQL command. I recive the error only up to 1000 characters are allowed in an SQL command. I read that SQLite can handel up to 1 million characters. How I can grow up the limitation in R code?

Thanks

**Comment by krlmlr** [comment]
This is a limitation of R, I have found the following workaround:

- Register rlang as error handler as described in https://rlang.r-lib.org/reference/rlang_backtrace_on_error.html
- Call `rlang::last_error()` after the error has occurred

Does this work for you? It would be great to have this documented somewhere, as this also affects other backends.

**Comment by krlmlr** [comment]
Stale, closing.
