### ISSUE TITLE
Can't change sqlite3_config(SQLITE_CONFIG_MULTITHREAD)

### ISSUE THREAD

**Issue by rodriguesk** [r-dbi/RSQLite#307]
Need to be able to set the configuration for SQLite database to MULTITHREAD. Currently not available in this RSQLite API. But is available in the C API: https://www.sqlite.org/capi3ref.html#sqliteconfigmultithread

Can you port this MULTITHREAD option to RSQLite please?

**Comment by krlmlr** [comment]
Thanks. I'm not sure I understand. This seems to be a compile-time configuration?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
