### ISSUE TITLE
Valid field.types parameter passed to dbWriteTable raises error

### ISSUE THREAD

**Issue by rcfree** [r-dbi/RSQLite#309]
Between v2.1.0 and v2.1.1 it appears that validation was added to the dbWriteTable function (in table.R) to ensure field.types is a character vector. However, it looks like there may be a problem with this validation when a list (rather than the default 'NULL') is supplied as the parameter.

In v2.0 this worked: 
```R
DBI::dbWriteTable(conn,name="mytable",value=my.dataframe, field.types=list(term_id="COLLATE BINARY",term_status="",term_30="",term_60="",term_198=""),overwrite=TRUE,header=FALSE,row.names=FALSE)
``` 

But in v2.2 I now receive the error: 
```
`field.types` must be a named character vector with unique names, or NULL
```

Looking at the code it seems that this block in table.R:
```R
if (!is.null(field.types) && !(is.character(field.types) && !is.null(names(field.types)) && !anyDuplicated(names(field.types)))) {
      stopc("`field.types` must be a named character vector with unique names, or NULL")
    }
```

Could be changed to this. This would handle duplicates and non-lists:
```R
if (!is.null(field.types) && !is.list(field.types) || anyDuplicated(names(field.types))) {
      stopc("`field.types` must be a named character vector with unique names, or NULL")
    }
```
I would be happy to create a pull request for this if you agree with the change.

**Comment by krlmlr** [comment]
Thanks for catching this, happy to take the pull request.

Do we want to adapt tests in DBItest, or perhaps add tests here?

**Comment by rcfree** [comment]
I've had a look at the test suites in DBItest and RSQLite and it looks to me like the most appropriate place would be `test-dbWriteTable.R` in RSQLite. If you agree, I am happy to add a few tests to that file as part of the pull request.

**Comment by rcfree** [comment]
I've had another look at this and it may be due to an misunderstanding on my part as to what the function is expecting. If I change it from a list to a vector it works fine:
```R
DBI::dbWriteTable(conn,name="mytable",value=my.dataframe, field.types=c(term_id="COLLATE BINARY",term_status="",term_30="",term_60="",term_198=""),overwrite=TRUE,header=FALSE,row.names=FALSE)
```

Unless you suggest otherwise I will not submit a pull request.
