### ISSUE TITLE
Can't create in memory database when package installed to path with umlaut

### ISSUE THREAD

**Issue by EntwicklR** [r-dbi/RSQLite#310]
The dbConnect(RSQLite::SQLite(), ":memory:") method throws an error "Error: Failed to load extension: The specified module could not be found." if there are non Unicode characters in the path, where the library is installed. 
I use checkpoints which are stored in a subfolder of my R project. Now if someone moves the project to a folder with an Umlaut in the filepath, the scripts can not be executed any longer.

**Comment by krlmlr** [comment]
Thanks. Could you please run the following for troubleshooting:

``` r
library(RSQLite)
x <- getLoadedDLLs()[["RSQLite"]][["path"]]
x
#> [1] "/home/kirill/R/x86_64-pc-linux-gnu-library/3.6/RSQLite/libs/RSQLite.so"
Encoding(x)
#> [1] "unknown"
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtmorgan** [comment]
This seems to have caused problems for a user, with the diagnosis somewhere around https://support.bioconductor.org/p/125780/#130218 . Maybe RSQLite could check for unsupported paths and fail to load with an informative error message? Maybe that is the direction the previous comment was heading in...

**Comment by mchldgd** [comment]
I had a similar problem, resolved thanks to the help of mtmorgan.
When RSQLite is installed in the path "C:/Users/Propriétaire/Documents/R/win-library/3.6" containing the "é" character, I have the following message:
```

> example(RSQLite)

RSQLit> library(DBI)

RSQLit> # Initialize a temporary in memory database and copy a data.frame into it
RSQLit> con <- dbConnect(RSQLite::SQLite(), ":memory:")
Error: Failed to load extension: Le module spécifié est introuvable.
```
("Le module spécifié est introuvable" means that R can't fin the module, in french)

And when I run the troubleshooting proposed by krlmlr, I have:

```
> library(RSQLite)
> x <- getLoadedDLLs()[["RSQLite"]][["path"]]
> x
[1] "C:/Users/Propriétaire/Documents/R/win-library/3.6/RSQLite/libs/x64/RSQLite.dll"
> Encoding(x)
[1] "unknown"
```

**Comment by krlmlr** [comment]
Thanks.

SQLite expects everything to be UTF-8, also the path names for extensions. We need to add an `enc2utf8()`.
