### ISSUE TITLE
Database keeps locking on Ubuntu

### ISSUE THREAD

**Issue by jsilve24** [r-dbi/RSQLite#312]
Hi all, 

I am using Ubuntu 16.04 (can't upgrade as this is a virtual machine at my university), RSQLite (2.2.0), R version 3.6.2. 

---

The following code works fine on my personal mac but throws 

```
Error: database is locked
Error: database is locked
```
on the Ubuntu machine. 

```r
library(tidyverse)
library(dbplyr)


db_file <- "foo.db"
db <- RSQLite::dbConnect(RSQLite::SQLite(), db_file)

foo <- data.frame(a=1:50000, b=1:50000)
RSQLite::dbWriteTable(db, "encounters", foo, overwrite=TRUE, temporary=FALSE)
```
Any idea why this is happening and how to fix?

**Comment by jsilve24** [comment]
of note, the filesystem of the VM I am using is cifs. Not sure if that is important... 

I only mention it because of section 2.3 here:
https://www.sqlite.org/howtocorrupt.html#_two_processes_using_different_locking_protocols

**Comment by krlmlr** [comment]
Is the sqlite3 command line client installed on the system? Does that work on this particular file system?

Which part of code throws the errors? Can you please run with [reprex](https://reprex.tidyverse.org/)?

**Comment by krlmlr** [comment]
Closing because information is missing and no feedback has been provided. For related problems, please open a new issue and add a link to this issue.
