### ISSUE TITLE
Update SQLite version to current stable version  3.32.3

### ISSUE THREAD

**Issue by wiligl** [r-dbi/RSQLite#321]
I propose to update the included SQLite version in the RSQLite package to the current stable version 3.32.3 and update the current R package version on CRAN [2], which currently includes version 3.22. Alternatively, it would be helpful to allow in the RSQLite package to define the path to a user-defined installation of a (current) SQLite version.

The reason is that current SQLite version 3.22 does not implement important functions of the SQL standard such as "windowing functions" incl RANK(), OVER() etc.

Workaround solutions are also welcome!

Thanks, Wilmar

## CODE example runs only under SQLite version 3.32, but not 3.22:
select sqlite_version();

drop table if exists tt;
drop table if exists tt2;

create table tt(a text, b int);
insert into tt(a,b) VALUES ('A',11),('A',22),('B',33),('B',44);

create table tt2 as
select *, ROWID as c, RANK() OVER(PARTITION BY a ORDER BY b) as d
from tt;

select * from tt;
select * from tt2;

Refs:
[1] https://www.sqlite.org/download.html
[2] https://cran.r-project.org/web/packages/RSQLite/index.html

**Comment by emilyriederer** [comment]
I would also love this update! It seems like 3.32 adds quite a lot. I just installed the `dev` version to get up to 3.31 but am really after the `iif()` function (if-then-else one liner) that's only came in 3.32.
