### ISSUE TITLE
dbReadTable() to write CSV data

### ISSUE THREAD

**Issue by kmishra9** [r-dbi/RSQLite#322]
A nearly identical issue to #151 -- it'd be ideal to be able to stream a table to disk from a SQLite db without having to load it to memory first! 

Desired workflow:
```r
DBI:: dbReadTable(conn = sqlite_connection, name = 'test_table', value = '~/test_table.CSV')
```

**Comment by krlmlr** [comment]
Are you looking for `dbWriteTable(conn, "test_table", "test_table.csv")` ?

**Comment by kmishra9** [comment]
To be clear, I think what I'm asking for is the opposite of that. The provided code will load `test_table.csv` into conn as `test_table` (which is awesome when working with big data because it doesn't require loading to memory like `copy_to()` does), but there's no equivalent for writing out from SQL **to CSV** (or other format) without pulling into memory, which means I have to hop into a SQL IDE to do so and makes stuff not 100% reproducible from scripts alone

**Comment by krlmlr** [comment]
I was confused.

Would arkdb solve your use case? https://docs.ropensci.org/arkdb/

**Comment by kmishra9** [comment]
Ah, I vaguely recall taking a look at this a few months ago. I believe the issue was that I think arkdb can archive the entire DB but you can't specify a single table, which was key for my use case, since the DB I'm working with is both slow and relatively massive compared to the single file I wanted to extract (which was still too large for the memory of VM) :/

**Comment by krlmlr** [comment]
`arkdb::ark()` seems to have a `tables` argument now: https://docs.ropensci.org/arkdb/reference/ark.html.

**Comment by kmishra9** [comment]
Ah. That's either new or I never dove deep enough into the package beyond some initial vignettes! 

But thanks, that's helpful and should solve my use case :)
