### ISSUE TITLE
help needed for blob

### ISSUE THREAD

**Issue by splaisan** [r-dbi/RSQLite#330]
Could you please point me to a working shiny example that stores a computer file (PDF, DOC, and/or XLS) into a SQLite **blob** record as well as the code to later convert back the blob into a file.

I have tried some google commands with serialize but failed to get a working command set.

```
conn <- dbConnect(RSQLite::SQLite(), paste0(DBpath, "/", DBfile))
file <- "/path/to/some/file.pdf"
fcontent <- readBin(con = file, what = raw(), n = file.info(file)$size)
content <- serialize(fcontent, NULL)  
pid=1 # for testing
name=basename(file)
ext=tools::file_ext(file)
query <- paste0("INSERT INTO ProjectDocs (
                    ProjectID,
                    Name,
                    Extension,
                    Document
                    ) VALUES (",
                            "", pid, ", ",
                            "'", name, "', ",
                            "'", ext, "', ",
                            "'", content, "' ",
                            ")")
res <- dbSendQuery(conn, query)
dbClearResult(res)
```

I seem to get multiple small hex strings sent instead of one blob piece, how can I merge all the pieces of the serialized object into a single blob and store it in a single row of my DB.
Thanks

**Comment by krlmlr** [comment]
I strongly advise to use parametrized queries, see [`?dbBind`](https://dbi.r-dbi.org/reference/dbbind). To store a BLOB value, you need to wrap it in a list. You should be able to use something like

```r
query <- "INSERT INTO ... (...) VALUES ($pid, $name, $ext, $content)"
dbExecute(conn, query, values = list(pid = pid, ..., content = list(fcontent)))
```

I wonder where the documentation can be improved to make this easier to discover?

**Comment by krlmlr** [comment]
Now documented in `vignette("DBI-advanced", package = "DBI")` .

**Comment by splaisan** [comment]
Thanks a lot
