### ISSUE TITLE
Rstudio Connection pane opens also when RSQlite called from inside a function

### ISSUE THREAD

**Issue by giocomai** [r-dbi/RSQLite#369]
I have a package that calls different SQLite databases for caching. Starting with RSQLite 2.2.6, if I use this package in Rstudio I just see the connections pane continuosly opening and closing, with no apparent way to disable this behaviour (even if I hide this from the settings, it appears again as soon as a new connection to SQLite is made from inside a function). This is annoying, and, I suspect is the cause for otherwise unexpected `R code execution errors` that I get from the Rstudio IDE.

I am reporting this here, however, as I understand that a better implementation of the Rstudio connection contract would make it possible to have the connection pane opened only when `RSQlite` is called from outside a function. If it is called from within a function, then the pane would not appear. 

For details, see in particular [this post in the Rstudio community](https://community.rstudio.com/t/database-connections-pane/43230/2?u=giocomai), which refers to how the ODBC package [implements this](https://github.com/r-dbi/odbc/blob/7b35549f9df935e1d132f6221860f87a6eb64ef6/R/Driver.R#L115).

Shouldn't this be the default behaviour of RSQlite as well?

In brief, in a scenario such as the following, I believe the connection pane should not appear:

```r
test <- function(){
  con <- dbConnect(RSQLite::SQLite(), ":memory:")
  return(con)
}
test()
```
If more examples are needed, I'm happy to provide further reference to real world scenarios, but I'm sure you can esily imagine a function working with different sqlite databases that when called leads to a whirlwind of action in the connection pane that I'm sure is undesirable for most users. 

I understand that this behaviour can be disabled with `options(connectionObserver = NULL)`, but it took more than I care to admit to find this out as it is not clearly referenced in the documentation. 

If you feel that instead the current behaviour is desirable, I would appreciate suggestions on a way for packages that depend on RSQLite to opt out of the integration with the Rstudio connections pane. Thanks!

**Comment by krlmlr** [comment]
CC @edwindj.

**Comment by travis-m-blimkie** [comment]
I've been experiencing this same issue, which has been causing my shiny apps to crash because of unwanted connections being opened to other packages/functions. Downgrading to 2.2.5 seems to solve the problem for now, but I'd also be interested in a better solution (the `options` call seems like an OK start).

**Comment by krlmlr** [comment]
The feature has been removed in RSQLite 2.2.7, pending investigation.
