### ISSUE TITLE
dbColumnInfo() should return SQL Data Types

### ISSUE THREAD

**Issue by ankane** [r-dbi/RSQLite#388]
Hi, is there a way to get SQL column types from a result with RSQLite? It looks like `dbColumnInfo` only returns the R data type.

I think this is related to r-dbi/RSQLite#37.

**Comment by gavril0** [comment]
`dbColumnInfo()` does not yet work wth RSQLite (Package version: RSQLite_2.2.7, DBI_1.1.1)

```
con<-dbConnect(RSQLite::SQLite(), ":memory:")

test <- data.frame(id=1:3, text=rep("text",3)) 
dbWriteTable(con, "t1", test, overwrite=TRUE)
dbReadTable(con, "t1")
dbColumnInfo(con,"t1")`
=>  unable to find an inherited method for function ‘dbColumnInfo’ 
      for signature ‘"SQLiteConnection"

dbCreateTable(con, "t2", fields=list(id="INTEGER", text="TEXT") )
dbReadTable(con, "t2")
dbColumnInfo(con,"t2")
=>  unable to find an inherited method for function ‘dbColumnInfo’ 
      for signature ‘"SQLiteConnection"
```

This is also the case when using ` dbCreateTable`  even though types are explicit.ely
defined.  

```
dbCreateTable(con, "t3", fields=list(id="INTEGER", text="UNKNOWN TYPE") )
```

By the way, it `dbCreateTable` seems that any type can be used to with `dbCreateTable`.
It is not clear what is actually created in the database.  Perhaps, it should raised an error/warning?

In any case, it would be nice if `dbColumnInfo()` returned the types according to [SQLite specs](https://www.sqlite.org/datatype3.html) (i.e. return the type actually used in the SQLite database) rather than types defined at the higher level.

**Comment by krlmlr** [comment]
Returning the actual type requires scanning the data, because in SQLite, a column can have different contents in each row.

**Comment by ankane** [comment]
Hey @krlmlr, for SQL types, I think it'd be best to return the declared type with [sqlite3_column_decltype](https://www.sqlite.org/c3ref/column_decltype.html), similar to how the Ruby gem does it:

```ruby
require "sqlite3"

db = SQLite3::Database.new(":memory:")
db.execute("CREATE TABLE users (id integer, active boolean, properties json)")
p db.query("SELECT * FROM users").types
```

This outputs `["integer", "boolean", "json"]`.

**Comment by krlmlr** [comment]
I wonder how bad it would be if RSQLite really used only the declared column types, and returned `NA` if the type of the contents didn't match. Maybe we can make this an option to `dbConnect()` ?

**Comment by ankane** [comment]
It's an interesting idea for an option (that's essentially what I'm looking to do for [date, time, and boolean columns](https://github.com/ankane/dbx/#data-type-limitations) for dbx), but I think it'd still be useful to have a way to get the declared types from a result.

fwiw, Ruby's most popular SQLite library ignores the declared type.

```ruby
require "sqlite3"

db = SQLite3::Database.new(":memory:")
db.execute("CREATE TABLE users (id integer, active boolean, properties json)")
db.execute("INSERT INTO users VALUES ('string', 'string2', 123)")
res = db.query("SELECT * FROM users")
p res.types # ["INTEGER", "boolean", "json"]
p res.to_a  # [["string", "string2", 123]]
```

**Comment by krlmlr** [comment]
Thanks. This is what we do here too, it's a big pain.

I agree that the library should just return whatever types are declared, even if it's wildly inconsistent.

**Comment by ankane** [comment]
Cleaning up stale issues
