### ISSUE TITLE
"Interrupt in busy handler" fails in Debian testing

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/RSQLite#406]
@gaborcsardi: Do you have a Debian at hand to take a quick look?

https://www.r-project.org/nosvn/R.check/r-release-linux-x86_64/RSQLite-00check.html

```
checking tests ... [18s/21s] ERROR
  Running ‘testthat.R’ [18s/20s]
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(RSQLite)
  >
  > test_check("RSQLite")
  [ FAIL 1 | WARN 0 | SKIP 6 | PASS 595 ]
  
  == Skipped tests ===============================================================
  * NYI (1)
  * On CRAN (2)
  * On Linux (2)
  * astyle not found (1)
  
  == Failed tests ================================================================
  -- Failure (test-dbConnect.R:191:3): interrupt in busy handler -----------------
  gsub("\r", "", out$stdout) not equal to "caught error\ndone\n".
  1/1 mismatches
  x[1]: ""
  y[1]: "caught error\ndone\n"
  
  [ FAIL 1 | WARN 0 | SKIP 6 | PASS 595 ]
  Error: Test failures
  In addition: Warning message:
  call dbDisconnect() when finished working with a connection
  Execution halted
```

**Comment by gaborcsardi** [comment]
Are you still embedding sqlite? Or this is with the one that comes from Debian? I am just trying to see why this popped up now. What has changed?

**Comment by krlmlr** [comment]
This popped up after the 2.2.10 release, which adds tests for `sqliteSetBusyHandler()` and upgrades to SQLite 3.37.2. I'm still embedding SQLite.

**Comment by krlmlr** [comment]
https://github.com/r-dbi/RSQLite/pull/401

**Comment by gaborcsardi** [comment]
Ah, so this is a new test case. Sorry, I missed that.

**Comment by krlmlr** [comment]
It seems that these failures are spontaneous. I'm skipping for now, let's see if these occur in the wild.

**Comment by krlmlr** [comment]
Seems stable enough now.
