### ISSUE TITLE
Error  in dbConnect or even loading library in Windows 11

### ISSUE THREAD

**Issue by xmart** [r-dbi/RSQLite#425]
Error  in dbConnect or even loading library in Windows 11

---

I installed `RSQLite` package and then tried to run tutorial. An error happened, I searched stackoverflow, updated `rlang`, updated `Rcpp`, changed to a no-space-in-name path, without results.  
I can not even load library. Errors below.

```r
> library(DBI)
> mydb <- dbConnect(RSQLite::SQLite(), "my-db.sqlite")
Error in h(simpleError(msg, call)) : 
  erro na avaliação do argumento 'drv' na seleção do método para a função 'dbConnect': '.onLoad falhou em loadNamespace() para 'RSQLite', detalhes:
  chamada: NULL
  erro: 'hash' is not an exported object from 'namespace:rlang''
> library(RSQLite)
Error: package or namespace load failed for ‘RSQLite’:
 .onLoad falhou em loadNamespace() para 'RSQLite', detalhes:
  chamada: NULL
  erro: 'hash' is not an exported object from 'namespace:rlang'
```

**Comment by krlmlr** [comment]
Thanks. Can you please try updating the rlang package?

**Comment by xmart** [comment]
> Thanks. Can you please try updating the rlang package?

Tks and sorry! I could swear I had already updated it!
