### ISSUE TITLE
Insert ID, last_insert_rowid and race condition

### ISSUE THREAD

**Issue by SarenT** [r-dbi/RSQLite#426]
Often it is suggested to use last_insert_rowid() to get the most recent insert ID. However, there can be a race condition and the recent ID may be different from the expected one. Is there any better method? dbBind does not return the ID but only the affected rows.

**Comment by krlmlr** [comment]
Take a look at `dplyr::rows_append(in_place = TRUE, returning = ...)` , this needs the dev version of dbplyr.

The SQL equivalent is the `RETURNING` clause, you can use `INSERT INTO ... RETURNING` with `dbGetQuery()` .

**Comment by SarenT** [comment]
Thanks returning did the trick for me.
