### ISSUE TITLE
RSQLite crash during install

### ISSUE THREAD

**Issue by chodarq** [r-dbi/RSQLite#440]
Hi.
I'm try to install RSQLite package from my R console, using R version 4.2.1.
I use install.packages("RSQLite") (or using devtools) and after a long list of lines (attached in file _completelog_RSQLite.txt_), my computer crash everytime in this line:
...
g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RSQLite.so DbColumn.o DbColumnDataSource.o DbColumnDataSourceFactory.o DbColumnStorage.o DbConnection.o DbDataFrame.o DbResult.o RcppExports.o SqliteColumnDataSource.o SqliteColumnDataSourceFactory.o SqliteDataFrame.o SqliteResult.o SqliteResultImpl.o affinity.o connection.o ext-csv.o ext-math.o ext-regexp.o ext-series.o extensions.o import-file.o result.o rsqlite.o vendor/sqlite3/sqlite3.o -L/usr/lib/R/lib -lR

After that, my PC restart. This occurs if I try to install from R in console, GUI, RStudio, from putty session, etc....Any idea?
Thanks in advance.

[completelog_RSQLite.txt](https://github.com/r-dbi/RSQLite/files/9805602/completelog_RSQLite.txt)

**Comment by krlmlr** [comment]
Thanks, this is weird. Is your system running out of random access memory (RAM) by any chance?

**Comment by chodarq** [comment]
I don't think so.
I tried in a fresh ubuntu 22 installation, with 32 Gb of ram.
I have an old laptop with 8gb and run without problem, but in windows.

**Comment by krlmlr** [comment]
Memory may run out if you compile in parallel, e.g., with a custom configuration in `~/.R/Makevars` .

I've never seen a computer *restart* as a result of compiling a package. Is the hardware intact?

Would that crash also occur in Docker so that we can try replicating it elsewhere?

**Comment by chodarq** [comment]
Hi.
There is nothing compile in parallel. 
I've never see also, and that's why I am very confused. About the hardware, I assume that everything is correct. I try in two different drives (WD-SSD-480Gb and WD-RedNAS-2Tb), both with fresh installations, and the problem it's the same. Also, memtest86 did not show any problem. Heat does not exceed 35-40 °C. And it's only ocurrs when I try to install RQSLite. All the other packages that I have installed so far are working.
About the Docker...never try.

**Comment by krlmlr** [comment]
The CPU? Some firmware that needs to be applied?

To work around, you could install binaries from RStudio Package Manager: https://packagemanager.rstudio.com/client/#/ .

You could try specifying a different compiler in `~/.R/Makevars` . Double-check with `R CMD config CXX` .

**Comment by chodarq** [comment]
I will check CPU tomorrow.
Also the binaries and compiler.
Thanks for your time.

**Comment by chodarq** [comment]
An update... binary works perfectly!

**Comment by krlmlr** [comment]
Thanks for the heads-up!
